version: '3.8'
services:
    db:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: FIAPOficina
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        networks:
            - FIAPOficina
        volumes:
            - db_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "root@root.com"
            PGADMIN_DEFAULT_PASSWORD: "root"
        ports:
            - "16543:80"
        networks:
            - FIAPOficina
        depends_on:
            - db
    sonarqube:
        image: sonarqube:lts-community
        depends_on:
            - db
        environment:
            - SONARQUBE_JDBC_USERNAME=root
            - SONARQUBE_JDBC_PASSWORD=root
            - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
        ports:
            - "9000:9000"
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
networks:
    FIAPOficina:
        driver: "bridge"
volumes:
    db_data:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
